package OrderManagement;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrei
 */
import java.awt.event.ActionListener;

public class Fatada extends javax.swing.JFrame {

    private static Warehouse w = new Warehouse();

    /**
     * @return the name
     */
    public static javax.swing.JTextField getNume() {
        return name;
    }

    /**
     * @return the bucati
     */
    public static javax.swing.JTextField getBucati() {
        return bucati;
    }

    /**
     * se invalideaza butonul submit si se valideaza butonul Client nou
     */
    public static void setSubmit() {
        submit.setEnabled(false);
        newCustomer.setEnabled(true);

    }

    /**
     * se reseteaza campurile de introducere a datelor clientului
     */
    public static void setNewCustomer() {
        name.setText("");
        forname.setText("");
        cnp.setText("");
        newCustomer.setEnabled(false);
        submit.setEnabled(true);
    }

    /**
     * @return the afisor
     */
    public static javax.swing.JTextArea getAfisor() {
        return afisor;
    }

    /**
     * @param aAfisor the afisor text to set
     */
    public static void setAfisor(String aAfisor) {
        afisor.setText(aAfisor);
    }

    /**
     * @param aPretTotal the text of pretTotal to set
     */
    public static void setPretTotal(String aPretTotal) {
        pretTotal.setText(aPretTotal + "$");
    }

    /**
     * @param aPretUnitar the text of pretUnitar to set
     */
    public static void setPretUnitar(String aPretUnitar) {
        pretUnitar.setText(aPretUnitar + "$");
    }

    /**
     * clean the afisor field
     */
    public static void setAfisor() {
        afisor.setText("");
    }
    ActionListener listener = new ClickListener();

    /** Creates new form Fatada */
    public Fatada() {
        initComponents();
        actions();
    }

    /**
     * adauga ActionListenerul la cele 4 butoane
     *  se initialezeaza comboboxul cu numele produselor din Warehouse
     */
    public void actions() {
        w.adaugaIterator();
        adauga.addActionListener(listener);
        confirma.addActionListener(listener);
        submit.addActionListener(listener);
        newCustomer.addActionListener(listener);
        String d = products.getSelectedItem().toString();
        int y = w.find(d).getProduct().getPret();
        w.adaugaIterator();
        int q = w.find(d).getNrUnitati();
        informatii.setText("pret:" + y + "  bucStoc:" + q);
        pretUnitar.setText(Integer.toString(y) + "$");
//   pretUnitar.setText(Integer.toString(y*Integer.parseInt(bucati.getText()))+"$");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        forname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cnp = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        informatii = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pretUnitar = new javax.swing.JLabel();
        pretTotal = new javax.swing.JLabel();
        adauga = new javax.swing.JButton();
        confirma = new javax.swing.JButton();
        products = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        afisor = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        bucati = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        newCustomer = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("OrderManagement"), this, org.jdesktop.beansbinding.BeanProperty.create("title"), "");
        bindingGroup.addBinding(binding);

        jPanel1.setBackground(new java.awt.Color(153, 255, 0));

        jLabel1.setText("Nume:");

        jLabel2.setText("Prenume:");

        name.setText("ion");

        forname.setText("cardan");

        jLabel3.setText("CNP:");

        cnp.setText("132");

        jLabel4.setText("Modalitate plata");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Card");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Cash la primire");

        jLabel5.setText("Informatii");

        informatii.setEditable(false);

        jLabel6.setText("Pret");

        jLabel7.setText("Pret total");

        pretUnitar.setText("0$");

        pretTotal.setText("0$");

        adauga.setText("Adauga");

        confirma.setText("Confirma");

        products.setModel(new javax.swing.DefaultComboBoxModel(w.getNumeProduse()));
        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });

        jLabel10.setText("Tip produs");

        afisor.setColumns(20);
        afisor.setEditable(false);
        afisor.setRows(5);
        jScrollPane1.setViewportView(afisor);

        jLabel11.setText("Nr de bucati:");

        bucati.setText("1");
        bucati.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bucatiKeyPressed(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        newCustomer.setText("Client nou");
        newCustomer.setEnabled(false);

        jLabel8.setText("Nume |   Pret unitar |   Buc  |  Cod");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(39, 39, 39)
                                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(forname))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(46, 46, 46)
                                                .addComponent(cnp)))
                                        .addGap(111, 111, 111))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(newCustomer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(submit)
                                        .addGap(74, 74, 74)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pretUnitar)
                                            .addComponent(pretTotal)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addComponent(jLabel11))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(bucati, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(products, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(informatii, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(adauga))))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(confirma, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bucati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(forname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(submit)
                                    .addComponent(newCustomer))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(informatii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adauga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pretUnitar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel7)
                    .addComponent(pretTotal))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addGap(82, 82, 82)
                        .addComponent(confirma))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-680)/2, (screenSize.height-540)/2, 680, 540);
    }// </editor-fold>//GEN-END:initComponents

   public static void setInformatii(String s){
       informatii.setText(s);
   }

    /**
     * se implementeaza actionPerformed pentru comboBox
     * @param evt evenimentul declansator
     */
    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
        w.adaugaIterator();
        String d = products.getSelectedItem().toString();
        int y = w.find(d).getProduct().getPret();
        w.adaugaIterator();
        int q = w.find(d).getNrUnitati();
        informatii.setText("pret:" + y + "  bucStoc:" + q);

        pretUnitar.setText(Integer.toString(y * Integer.parseInt(bucati.getText())) + "$");
    }//GEN-LAST:event_productsActionPerformed
    /**
     *pentru iesirea din aplicatie
     * @param evt evenimentul declansator
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /**
     * implementeaza AcctionListener pentru campul de text care contine numarul de bucati
     * @param evt evenimentul declansator
     */
    private void bucatiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bucatiKeyPressed
        System.out.println(evt.getKeyChar());
        w.adaugaIterator();
        String d = products.getSelectedItem().toString();
        int y = w.find(d).getProduct().getPret();
        try {
            int k = Integer.parseInt(bucati.getText()) * 10 + Integer.parseInt(Character.toString(evt.getKeyChar()));
            pretUnitar.setText(Integer.toString(y * k) + "$");
        } catch (NumberFormatException ex) {
            System.out.println(evt.getKeyCode());
            try {
                pretUnitar.setText(Integer.toString(y * Integer.parseInt(bucati.getText())) + "$");
            } catch (NumberFormatException exe) {
            }
        }
    }//GEN-LAST:event_bucatiKeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed
    /**
     * 
     * @return produsul cumparat
     */
    public static Product produsulCumparat() {
        w.adaugaIterator();
        String d = products.getSelectedItem().toString();
        return w.find(d).getProduct();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Fatada().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adauga;
    private static javax.swing.JTextArea afisor;
    private static javax.swing.JTextField bucati;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JPasswordField cnp;
    private javax.swing.JButton confirma;
    private static javax.swing.JTextField forname;
    private static javax.swing.JTextField informatii;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextField name;
    private static javax.swing.JButton newCustomer;
    private static javax.swing.JLabel pretTotal;
    private static javax.swing.JLabel pretUnitar;
    private static javax.swing.JComboBox products;
    private static javax.swing.JButton submit;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cnp
     */
    public static javax.swing.JPasswordField getCnp() {
        return cnp;
    }

    /**
     * @return the forname
     */
    public static javax.swing.JTextField getForname() {
        return forname;
    }

    /**
     * @return the informatii
     */
    public static javax.swing.JTextField getInformatii() {
        return informatii;
    }

    /**
     * @param products the products to set
     */
    public void setProducts(javax.swing.JComboBox products) {
        this.products = products;
    }
}
